name: Build Qt6
on: push
env:
  RELEASE_TAG: packages

jobs:
  build:
    runs-on: windows-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix: 
        pkg: [ qt6-base ]
        version: [ 6.7.0 ]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-cmake mingw-w64-ucrt-x86_64-ninja mingw-w64-ucrt-x86_64-python
      - name: Build
        run: |
          _pkgfn = ${{ matrix.pkg/6-/ }}
          git clone -b v${{ matrix.version }}  https://code.qt.io/qt/${_pkgfn}.git
