name: Build Qt6

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: show
      shell: C:\shells\msys2bash.cmd {0}
      run: |
        ls -R
